name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: Login to docker registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker login
        run: docker login -u "${{ secrets.QUAY_IO_USER }}" -p "${{ secrets.QUAY_IO_PASSWORD }}" quay.io