name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f build/ci/.goreleaser.yml --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}